name: Daily NBA Dataset Downloader

on:
  schedule:
    - cron: '0 21 * * *'   # Runs at 7 AM Sydney time (AEST = UTC+10)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Kaggle
      run: pip install kaggle

    - name: Create kaggle.json from secret
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download NBA Dataset
      run: |
        kaggle datasets download -d eoinamoore/historical-nba-data-and-player-box-scores --unzip -p nba_dataset

    - name: List downloaded files
      run: ls -R nba_dataset
